default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: ayumi_elearning_development

test:
  <<: *default
  database: ayumi_elearning_test

production: 
  <<: *default
  database: ayumi_elearning_production
  username: ayumi-elearning_name
  password: <%= ENV['AYUMI_ELEARNING_DATABASE_PASSWORD'] %>
